//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileServer.Presentation.WinSite {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileManager_Spanish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileManager_Spanish() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileServer.Presentation.WinSite.FileManager.Spanish", typeof(FileManager_Spanish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string BOTON_GUARDAR {
            get {
                return ResourceManager.GetString("BOTON_GUARDAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AppConfig.
        /// </summary>
        internal static string CBOX_APPCONFIG {
            get {
                return ResourceManager.GetString("CBOX_APPCONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .json.
        /// </summary>
        internal static string CBOX_JSON {
            get {
                return ResourceManager.GetString("CBOX_JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .txt.
        /// </summary>
        internal static string CBOX_TXT {
            get {
                return ResourceManager.GetString("CBOX_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Variable de entorno.
        /// </summary>
        internal static string CBOX_VAR_ENT {
            get {
                return ResourceManager.GetString("CBOX_VAR_ENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .xml.
        /// </summary>
        internal static string CBOX_XML {
            get {
                return ResourceManager.GetString("CBOX_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        internal static string LABEL_APELLIDOS {
            get {
                return ResourceManager.GetString("LABEL_APELLIDOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        internal static string LABEL_CONFIGURACION {
            get {
                return ResourceManager.GetString("LABEL_CONFIGURACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DNI.
        /// </summary>
        internal static string LABEL_DNI {
            get {
                return ResourceManager.GetString("LABEL_DNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extensión.
        /// </summary>
        internal static string LABEL_EXTENSION {
            get {
                return ResourceManager.GetString("LABEL_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        internal static string LABEL_ID {
            get {
                return ResourceManager.GetString("LABEL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string LABEL_NOMBRE {
            get {
                return ResourceManager.GetString("LABEL_NOMBRE", resourceCulture);
            }
        }
    }
}
